/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.eurecom.calcite.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-09-03")
public enum ExprOption implements org.apache.thrift.TEnum {
  LITERAL(0),
  COLUMN(1),
  EXPR(2);

  private final int value;

  private ExprOption(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ExprOption findByValue(int value) { 
    switch (value) {
      case 0:
        return LITERAL;
      case 1:
        return COLUMN;
      case 2:
        return EXPR;
      default:
        return null;
    }
  }
}
