/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.eurecom.calcite.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-09-03")
public enum RelNodeType implements org.apache.thrift.TEnum {
  TABLE_SCAN(0),
  FILTER(1),
  JOIN(2),
  PROJECT(3),
  AGGREGATE(4),
  SORT(5);

  private final int value;

  private RelNodeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RelNodeType findByValue(int value) { 
    switch (value) {
      case 0:
        return TABLE_SCAN;
      case 1:
        return FILTER;
      case 2:
        return JOIN;
      case 3:
        return PROJECT;
      case 4:
        return AGGREGATE;
      case 5:
        return SORT;
      default:
        return null;
    }
  }
}
